### ISSUE TITLE
typescript类型DescriptionsColumns

### ISSUE THREAD

**Issue by flowerwOw0316** [pure-admin/pure-admin-descriptions#1]
// 这是组件库的类型
export interface DescriptionsColumns extends IDescriptionsItemInject {
    prop?: string;
    /** If filled, prop is invalid and data is no longer read from data */
    value?: string | number;
    hide?: CallableFunction;
    slot?: Readonly<{
        [name: string]: import("vue").Slot | undefined;
    }>;
    labelRenderer?: import("vue").FunctionalComponent | Function;
    cellRenderer?: import("vue").FunctionalComponent | Function;
}
// 这是element-plus官方的类型
export interface IDescriptionsItemInject {
    label: string;
    span: number;
    width: string | number;
    minWidth: string | number;
    align: string;
    labelAlign: string;
    className: string;
    labelClassName: string;
}
导致在定义column的时候使用ref<DescriptionsColumns>([xxx])在里面写的内容都是必填的

**Comment by xiaoxian521** [comment]
后续统一优化 这个组件哈 目前计划有点多 忙完后 回来优化 ❤️
